fun main() {
    println(run1pt1())
    println(run1pt2())
    println(run2pt1())
    println(run2pt2())
    println(run3pt1())
    println(run3pt2())
    println(run4pt1())
    println(run4pt2())
    println(run5pt1())
    println(run5pt2())
    println(run6pt1())
    println(run6pt2())
    println(run7pt1())
    println(run7pt2())
    println(run8pt1())
    println(run8pt2())
}
